# Generated by Django 5.0.1 on 2024-01-18 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_quality_rating', models.IntegerField(blank=True, null=True)),
                ('stress_rating', models.IntegerField(blank=True, null=True)),
                ('physical_health_rating', models.IntegerField(blank=True, null=True)),
                ('has_taken_meds', models.BooleanField(blank=True, null=True)),
                ('has_gotten_sunshine', models.BooleanField(blank=True, null=True)),
                ('has_eaten_healthily', models.BooleanField(blank=True, null=True)),
                ('has_connected_socially', models.BooleanField(blank=True, null=True)),
                ('has_exercised', models.BooleanField(blank=True, null=True)),
                ('has_used_substances', models.BooleanField(blank=True, null=True)),
                ('has_had_counseling', models.BooleanField(blank=True, null=True)),
                ('has_properly_hydrated', models.BooleanField(blank=True, null=True)),
                ('has_engaged_spiritually', models.BooleanField(blank=True, null=True)),
                ('has_menstruated', models.BooleanField(blank=True, null=True)),
                ('journal_entry', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main_app.profile')),
                ('emotion', models.ManyToManyField(to='main_app.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_counseling', models.BooleanField(default=False)),
                ('track_spirituality', models.BooleanField(default=False)),
                ('track_sleep', models.BooleanField(default=False)),
                ('track_stress', models.BooleanField(default=False)),
                ('track_physical_health', models.BooleanField(default=False)),
                ('track_meds', models.BooleanField(default=False)),
                ('track_sunshine', models.BooleanField(default=False)),
                ('track_eating_healthily', models.BooleanField(default=False)),
                ('track_connecting_socially', models.BooleanField(default=False)),
                ('track_exercise', models.BooleanField(default=False)),
                ('track_substances', models.BooleanField(default=False)),
                ('track_hydrated', models.BooleanField(default=False)),
                ('track_menstruation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='main_app.profile')),
            ],
        ),
    ]
