# Generated by Django 5.0.1 on 2024-01-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_emotion_dailyentry_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.emotion'),
        ),
    ]
