# Generated by Django 5.0.1 on 2024-01-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_emotion_dailyentry_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='timeline_color',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
