# Generated by Django 5.0.1 on 2024-01-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_emotion_parent'),
        ('main_app', '0003_emotion_timeline_color'),
    ]

    operations = [
    ]
