# Generated by Django 5.0.1 on 2024-01-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_20240122_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='track_connecting_socially',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='track_eating_healthily',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='track_exercise',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='track_sleep',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='track_sunshine',
            field=models.BooleanField(default=True),
        ),
    ]
